apiVersion: v1
data:
  000-default.conf: |
    <VirtualHost *:80>
    ServerName optimy-ci

    AddDefaultCharset utf-8

    DocumentRoot /optimy/admin-api-doc

    <Directory /optimy/admin-api-doc>
        Require all granted
        AllowOverride All
    </Directory>

    # setting CORS header for static resources
    <FilesMatch "\.(gif|jpe?g|png|eot|woff|ttf|svg|js)$">
        Header set Access-Control-Allow-Origin "*"
    </FilesMatch>

    # preventing our pages from being cached by a proxy or by the browser
    <FilesMatch "\.php$">
        ExpiresDefault A0
        Header set Cache-Control "no-store, no-cache, must-revalidate, max-age=0"
        Header set Pragma "no-cache"
    </FilesMatch>

    # preventing framing
    Header always append X-Frame-Options SAMEORIGIN

    # enabling browser XSS filter
    Header set X-XSS-Protection "1; mode=block"

    # preventing browser to do MIME-type sniffing
    Header set X-Content-Type-Options "nosniff"

    RewriteEngine On

    LogFormat "[APACHE] %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\""

    ErrorLog /dev/stdout
    TransferLog /dev/stdout

    php_admin_value open_basedir ".:/optimy/:/usr/share/php/:/logs/:/tmp/"
    php_admin_value include_path ".:/usr/share/php/"
    </VirtualHost>
kind: ConfigMap
metadata:
  name: ci-admin-api-doc-apache-config
